language: python
python:
  - "3.5"
before_script:
  - pip install pep8
script:
  - cp config.py.example config.py
  - cp options.py.example options.py
  - cp users.example users
  - cp ausers.example ausers
  - pep8 .
  - python3 tests.py
